### ISSUE TITLE
Password Recovery Not Working

### ISSUE THREAD

**Issue by Hailtothechimp78** [haswellr/CritterDB#97]
If this is a bug or issue report, please follow the template below:

**Actual Behavior**:
 -  `What is the issue?` I've attempted to recover my password a fair few times the past few days. I've yet to receive the email that would allow me to continue the process.
 -  `What is the expected behavior?` I've attempted password recovery a few times today, and a few yesterday. I'd like to think I'd have received the email by now to continue the process, but I have yet to do so.

**Additional Information**:
 -  `Browser Type:` Firefox
 -  `Browser Version:` 101.0.1 (64-bit)
 -  `OS:` Win 10

> Do not modify the titles or questions. Simply add your responses to the ends of the questions.
  Add more lines if needed.

**Comment by haswellr** [comment]
I received a couple other reports of this in the past couple of days, and should have made an issue for it. Thanks for doing so!

Something has gone wrong with the email service/code/etc. Given that it's the first time it's malfunctioned in years, without any recent changes on CritterDB's end, something has likely changed on Google's end. I suspect it's an easy fix. However, the bad news is that I'm on the road until July 5th without access to a computer, and I have been unable to correct the issue from my phone.

**Comment by Hailtothechimp78** [comment]
No worries! Glad making the issue helped you out!

I keep back up copies of stuff still, so being unable to log in shouldn't be too much of a problem for me until the problem is resolved.

Enjoy your trip!

    On Monday, June 20, 2022 at 08:25:59 PM CDT, Ryan Haswell ***@***.***> wrote:  
 
 


I received a couple other reports of this in the past couple of days, and should have made an issue for it. Thanks for doing so!

Something has gone wrong with the email service/code/etc. Given that it's the first time it's malfunctioned in years, without any recent changes on CritterDB's end, something has likely changed on Google's end. I suspect it's an easy fix. However, the bad news is that I'm on the road until July 5th without access to a computer, and I have been unable to correct the issue from my phone.

**Comment by haswellr** [comment]
Fixed. As of May 30th Gmail requires more secure authentication than it used to when sending emails, so CritterDB needed some updates. Sorry for the huge delay - bad timing as I was on the road all of June!

**Comment by Hailtothechimp78** [comment]
How long do you think it's going to take to update on either end? I'm still not receiving the email to reset my password.

**Comment by haswellr** [comment]
Hmm, it indeed wasn't working. After some fiddling it is back working, for me at least. Please give it another shot. I'll leave this issue open for a few days as I continue to monitor the issue periodically. I want to make sure the authentication isn't expiring or anything.

**Comment by Hailtothechimp78** [comment]
My apologies I've been so late with my reply. I just tried the process again and found success! Thanks again for all of your hard work!

    On Tuesday, July 5, 2022 at 09:40:28 PM CDT, Ryan Haswell ***@***.***> wrote:  
 
 


Hmm, it indeed wasn't working. After some fiddling it is back working, for me at least. Please give it another shot. I'll leave this issue open for a few days as I continue to monitor the issue periodically. I want to make sure the authentication isn't expiring or anything.
